spring:
  data:
    mongodb:
      host: codeserver.aniwoh.top
      port: 27017
      database: learnspringweb
    redis:
      host: codeserver.aniwoh.top
      port: 6379
      password: 123456

uploadPath: D:\Github\novelUpload