spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: learnspringweb
    redis:
      host: 127.0.0.1
      port: 6379

sa-token:
  cookie:
    same-site: None
    secure: true

server:
  reactive:
    session:
      cookie:
        same-site: none

uploadPath: D:\Github\novelUpload