spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: mySpringbootBlogPrd
    redis:
      host: host.docker.internal
      port: 6379
      password: 123456

uploadPath: /uploadPath