spring:
  application:
    name: mySpringbootBlog-api
  mvc:
    static-path-pattern: /static/**
  data:
    mongodb:
      host: 192.168.1.120
      port: 27017
      database: learnspringweb
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

server:
  port: 8888
