spring:
  data:
    mongodb:
      host: 192.168.1.120
      port: 27017
      database: learnspringweb
    redis:
      host: 192.168.1.120
      port: 6379
      password: 123456

uploadPath: D:\Github\novelUpload