spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: learnspringweb
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456

uploadPath: /data01/mySpringbootBlog-api/uploadPath