name: Build and Deploy Spring Boot

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy to Server
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the Spring Boot project using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build the Docker image
        run: docker build -t myspringbootblog-api .

      - name: Check Docker Image
        run: |
          docker images | grep myspringbootblog-api

      - name: Save images
        run: docker save -o /tmp/myspringbootblog-api.tar myspringbootblog-api

      - name: Verify Saved Tar File
        run: |
          ls -lh /tmp/myspringbootblog-api.tar

      - name: Upload images to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          target: ${{ secrets.TARGET_DIR }}
          source: /tmp/myspringbootblog-api.tar
          strip_components: 1
          args: "--overwrite"

      - name: Run docker on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker stop myspringbootblog-api
            docker rm myspringbootblog-api
            docker rmi myspringbootblog-api
            docker load -i myspringbootblog-api.tar
            docker run -d --name myspringbootblog-api -p 8888:8888 -v ${{ secrets.TARGET_DIR }}/uploadPath:/uploadPath myspringbootblog-api