name: Build and Deploy Spring Boot

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy to Server
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t myspringbootblog-api .

      - name: Check Docker Image
        run: |
          docker images | grep myspringbootblog-api

      - name: Save images
        run: docker save -o myspringbootblog-api.tar myspringbootblog-api

      - name: Verify Saved Tar File
        run: |
          ls -lh myspringbootblog-api.tar
          chmod 777 myspringbootblog-api.tar

      - name: Upload images to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          target: ${{ secrets.TARGET_DIR }}
          source: myspringbootblog-api.tar
          args: "--overwrite"

      - name: Run docker on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST_SSH }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop myspringbootblog-api
            docker rm myspringbootblog-api
            docker rmi myspringbootblog-api
            docker load -i ${{ secrets.TARGET_DIR }}/myspringbootblog-api.tar
            docker run -d --name myspringbootblog-api -p 8888:8888 -v ${{ secrets.TARGET_DIR }}/uploadPath:/uploadPath --add-host=host.docker.internal:host-gateway --restart=always  myspringbootblog-api