name: Build and Deploy Spring Boot

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy to Server
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the Spring Boot project using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Upload the JAR to the server
      - name: Upload JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          target: ${{ secrets.TARGET_DIR }}
          source: target/*.jar
          strip_components: 1
          args: "--overwrite"

      # Run the JAR on the serve
      - name: Run JAR on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            JAR_NAME="${{ secrets.JAR_NAME }}"; PID=$(ps aux | grep "$JAR_NAME" | grep -v grep | awk '{print $2}'); if [ -n "$PID" ]; then kill -9 $PID && echo "进程 $PID 已被杀死"; else echo "未找到与 $JAR_NAME 相关的进程"; fi
            nohup java -jar ${{ secrets.JAR_NAME }} > app.log 2>&1 &